.TH GMERLIN 1 "September 2021" Gmerlin "User Manuals"
.SH NAME
gmerlin \- Gmerlin Player
.SH SYNOPSIS
.B gmerlin 
.I [options]
.I [gmls
.I ...]
.SH DESCRIPTION
Gmerlin GUI Player
.SH OPTIONS

.B \-dbpath

.RS 2
Use other database path
.RE

.SH GENERIC OPTIONS
The following generic options are available for all gmerlin applications

.B \-help

.RS 2
Print this help message and exit
.RE

.B \-help\-man

.RS 2
Print this help message as a manual page and exit
.RE

.B \-help\-texi

.RS 2
Print this help message in texinfo format and exit
.RE

.B \-version

.RS 2
Print version info and exit
.RE

.B \-v
.I level

.RS 2
Set verbosity level (0..4)
.RE

.B \-syslog
.I name

.RS 2
Log to syslog the specified name
.RE

.B \-stderr

.RS 2
Always log to stderr
.RE

.SH FILES
.B ~/.gmerlin/plugins.xml

.RS 2
Cache of the plugin registry (shared by all applications)
.RE

.P
.B ~/.gmerlin/player/cfg.xml

.RS 2
Used for configuration data. Delete this file if you think you goofed
something up.
.RE

.P
.B ~/.gmerlin/player/tree/tree.xml

.RS 2
Media tree is saved here. The albums are saved as separate files in the same
directory.
.RE

.P
